DeltaApp/Controllers/ProcessN1Controller.cs
using DeltaApp.Models;
using DeltaApp.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DeltaApp.Controllers
{
    public class ProcessN1Controller : Controller
    {
        ProcessRepository ProcessRepository = new ProcessRepository();
        Process1Repository Process1Repository = new Process1Repository();

        // GET: Process
        public ActionResult Index()
        {
            return View();
        }

        #region Metodos jTable
        /// <summary>
        /// Obtener usuarios.
        /// </summary>
        /// <param name="name">Nombre de usuario</param>
        /// <param name="jtStartIndex"></param>
        /// <param name="jtPageSize"></param>
        /// <param name="jtSorting"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult GetProcess1(string name = "", int jtStartIndex = 0, int jtPageSize = 0, string jtSorting = null)
        {
            ActionResult result = null;
            try
            {
                //Lista de usuario con filtro
                var entities = this.Process1Repository.GetProcess1(name, jtStartIndex, jtPageSize, jtSorting);
                //Conteo de usuario con filtros
                var entitiesCount = this.Process1Repository.GetProcess1Count(name);
                //Resultado para contArea de jtable.
                result = Json(new { Result = "OK", Records = entities.ToList(), TotalRecordCount = entitiesCount }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                result = Json(new { Result = "ERROR", Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
            return result;
        }

        /// <summary>
        /// Obtener usuarios.
        /// </summary>
        /// <param name="processId0">Nombre de usuario</param>
        /// <param name="jtStartIndex"></param>
        /// <param name="jtPageSize"></param>
        /// <param name="jtSorting"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult GetProcess1ByProcess0(int processId0 = 0, int jtStartIndex = 0, int jtPageSize = 0, string jtSorting = null)
        {
            ActionResult result = null;
            try
            {
                //Lista de usuario con filtro
                var entities = this.Process1Repository.GetProcess1(processId0, jtStartIndex, jtPageSize, jtSorting);
                //Conteo de usuario con filtros
                var entitiesCount = this.Process1Repository.GetProcess1Count(processId0);
                //Resultado para contArea de jtable.
                result = Json(new { Result = "OK", Records = entities.ToList(), TotalRecordCount = entitiesCount }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                result = Json(new { Result = "ERROR", Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
            return result;
        }

        /// <summary>
        /// Crear nuevo tipo de servicio.
        /// </summary>
        /// <param name="entity">Informacion de usuario</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult CreateProcess1(PROCESS_N1_VIEW entity)
        {
            ActionResult result = null;
            string resultMessage = string.Empty;
            try
            {
                if (!this.ModelState.IsValid)
                {
                    throw new Exception("Form is not valid! Please correct it and try again.");
                }
                resultMessage = this.Process1Repository.Insert(entity);
                if (string.IsNullOrEmpty(resultMessage))
                {
                    result = this.Json(new { Result = "OK", Record = entity }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    result = this.Json(new { Result = "ERROR", Message = resultMessage }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                result = this.Json(new { Result = "ERROR", Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
            return result;
        }

        /// <summary>
        /// Actualizar tipo de servicio
        /// </summary>
        /// <param name="entity">Informacion de tipo de servicio</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult UpdateProcess1(PROCESS_N1_VIEW entity)
        {
            ActionResult result = null;
            string resultMessage = string.Empty;
            try
            {
                if (!this.ModelState.IsValid)
                {
                    throw new Exception("Form is not valid! Please correct it and try again.");
                }
                resultMessage = this.Process1Repository.Update(entity);
                if (string.IsNullOrEmpty(resultMessage))
                {
                    result = Json(new { Result = "OK" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    result = Json(new { Result = "ERROR", Message = resultMessage }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                result = Json(new { Result = "ERROR", Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
            return result;
        }

        /// <summary>
        /// Eliminar Area de usuario
        /// </summary>
        /// <param name="PROC_N0_ID">Id de Area de usuario</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult DeleteProcess1(int PROC_N1_ID)
        {
            ActionResult result = null;
            string resultMessage = string.Empty;
            try
            {
                resultMessage = this.Process1Repository.Delete(PROC_N1_ID);
                if (string.IsNullOrEmpty(resultMessage))
                {
                    result = this.Json(new { Result = "OK" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    result = this.Json(new { Result = "ERROR", Message = resultMessage }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                result = this.Json(new { Result = "ERROR", Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
            return result;
        }

        [HttpPost]
        public ActionResult GetProcess0Options()
        {
            try
            {
                var entities = this.ProcessRepository.GetAll()
                    .Select(c => new { DisplayText = c.PROC_N0_NAME, Value = c.PROC_N0_ID });
                return this.Json(new { Result = "OK", Options = entities });
            }
            catch (Exception ex)
            {
                return this.Json(new { Result = "ERROR", Message = ex.Message });
            }
        }
        #endregion Metodos jTable

    }
}

DeltaApp/Views/ProcessN1/Index.cshtml
<link href="~/Content/Views/ProcessN1/Index.css" rel="stylesheet" />

<script src="~/Scripts/Views/ProcessN1/Index.js"></script>

<script type="text/javascript">
    $(window).load(function () { $("#spinner").fadeOut("slow"); })
    $(document).ready(function () {
        var listCmd = '@this.Url.Action("GetProcess1", "ProcessN1")';
        var deleteCmd = '@this.Url.Action("DeleteProcess1", "ProcessN1")';
        var updateCmd = '@this.Url.Action("UpdateProcess1", "ProcessN1")';
        var createCmd = '@this.Url.Action("CreateProcess1", "ProcessN1")';
        ProcessN1Index.initializeComponents(listCmd, deleteCmd, updateCmd, createCmd);
    });
</script>
@using (Html.BeginForm("Index", "ProcessN1", FormMethod.Post, new { id = "formProcessN1" }))
{
    <div>
        <div>
            <h2 class="h2">Procedimiento N1</h2>
        </div>
    </div>

    <div>
        <div>
            <table style="width: 100%; text-align: center;">
                <tr>
                    <td>
                        <input id="txtName" name="txtName" placeholder="Nombre" type="text" />
                    </td>
                </tr>
            </table>
            <hr />
            <table style="width: 100%; text-align: center;">
                <tr>
                    <td>
                        <input type="submit" id="btnIndex" value="Atrás" class="input button" />
                        <input type="submit" id="btnSearch" value="Buscar" class="input button" />
                        <input type="submit" id="btnNewSearch" value="Nueva Búsqueda" class="input button" />
                    </td>
                </tr>
            </table>
        </div>
    </div>
    <div>
        <div>
            <hr />
        </div>
    </div>
    <div id="divProcessN1TableContainerValue"></div>
}