DeltaApp/Controllers/Report5Controller.cs
using DeltaApp.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Reporting.WebForms;
using DeltaApp.Repository;
using System.Drawing;
using System.IO;


namespace DeltaApp.Controllers
{
    public class Report5Controller : Controller
    {
        ReportsRepository reportRepository = new ReportsRepository();
        [ThreadStatic]
        ProcessRepository ProcessRepository = new ProcessRepository();

        // GET: Report1
        [AllowAnonymous]
        public ActionResult Index(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ViewResult Index(GENERAL_RESUME_VIEW um)
        {
            return View(um);
        }



        public ActionResult GenerateAndDisplayReport(string QdateFrom, string QdateTo, string format)
        {

            LocalReport pertDefects = new LocalReport();

            pertDefects.ReportPath = Server.MapPath("~/Reporting/DefectPertinences.rdlc");

            List<PERTINENCES_DEFECTS> listPertinencesDefects = reportRepository.GetPertinecesDefects(QdateFrom, QdateTo).ToList();

            ReportDataSource reportDataSource = new ReportDataSource();


            reportDataSource.Name = "DefectPertinences";

            if (QdateFrom != null && QdateTo != null)
            {
                var productDefects = listPertinencesDefects;
                
                reportDataSource.Value = productDefects;

            }
            else
            {
                reportDataSource.Value = reportDataSource;

            }



            pertDefects.DataSources.Add(reportDataSource);



            ReportParameterCollection reportParameters = new ReportParameterCollection();
            reportParameters.Add(new ReportParameter("DateFrom", QdateFrom));
            reportParameters.Add(new ReportParameter("DateTo", QdateTo));
            

            pertDefects.SetParameters(reportParameters);


            string reportType = "Image";
            string mimeType;
            string encoding;
            string fileNameExtension;
            //The DeviceInfo settings should be changed based on the reportType            
            //http://msdn2.microsoft.com/en-us/library/ms155397.aspx            
            string deviceInfo = "<DeviceInfo>" +
                "  <OutputFormat>jpeg</OutputFormat>" +
                "  <PageWidth>8.5in</PageWidth>" +
                "  <PageHeight>11in</PageHeight>" +
                "  <MarginTop>0.5in</MarginTop>" +
                "  <MarginLeft>1in</MarginLeft>" +
                "  <MarginRight>1in</MarginRight>" +
                "  <MarginBottom>0.5in</MarginBottom>" +
                "</DeviceInfo>";
            Warning[] warnings;
            string[] streams;
            byte[] reportBytes;


            //Render the report            
            reportBytes = pertDefects.Render(reportType, deviceInfo, out mimeType, out encoding, out fileNameExtension, out streams, out warnings);


            //Response.AddHeader("content-disposition", "attachment; filename=NorthWindCustomers." + fileNameExtension); 
            if (format == null)
            {
                return File(reportBytes, "image/jpeg");
            }
            else if (format == "PDF")
            {
                return File(reportBytes, "pdf");
            }
            else
            {
                /*var file = File(renderedBytes, "image/jpeg");

                var fileText = ImageToBase64(file, System.Drawing.Imaging.ImageFormat.Jpeg);*/

                return this.Json(new { Result = "OK", Report = Convert.ToBase64String(reportBytes) });
            }

        }

        static double F(double x)
        {
            MathNet.Numerics.Distributions.Normal result = new MathNet.Numerics.Distributions.Normal();
            return result.CumulativeDistribution(x);
        }

        public ActionResult DownloadReport(string territory, string format)
        {
            LocalReport localReport = new LocalReport();
            localReport.ReportPath = Server.MapPath("~/Reporting/DefectPertinences.rdlc");
            List<GENERAL_RESUME_VIEW> reportList = reportRepository.GetAll().ToList();
            ReportDataSource reportDataSource = new ReportDataSource();
            reportDataSource.Name = "General_Resume_View";
            if (territory != null)
            {
                var customerfilterList = from c in reportList
                                         where c.PDT_NAME == territory
                                         select c;


                reportDataSource.Value = customerfilterList;
            }
            else
                reportDataSource.Value = reportList;

            localReport.DataSources.Add(reportDataSource);
            string reportType = "Image";
            string mimeType;
            string encoding;
            string fileNameExtension;
            //The DeviceInfo settings should be changed based on the reportType            
            //http://msdn2.microsoft.com/en-us/library/ms155397.aspx            
            string deviceInfo = "<DeviceInfo>" +
                "  <OutputFormat>PDF</OutputFormat>" +
                "  <PageWidth>8.5in</PageWidth>" +
                "  <PageHeight>11in</PageHeight>" +
                "  <MarginTop>0.5in</MarginTop>" +
                "  <MarginLeft>1in</MarginLeft>" +
                "  <MarginRight>1in</MarginRight>" +
                "  <MarginBottom>0.5in</MarginBottom>" +
                "</DeviceInfo>";
            Warning[] warnings;
            string[] streams;
            byte[] renderedBytes;
            //Render the report            
            renderedBytes = localReport.Render(reportType, deviceInfo, out mimeType, out encoding, out fileNameExtension, out streams, out warnings);
            //Response.AddHeader("content-disposition", "attachment; filename=NorthWindCustomers." + fileNameExtension); 
            if (format == null)
            {
                return File(renderedBytes, "image/tiff");
            }
            else if (format == "PDF")
            {
                return File(renderedBytes, mimeType);
            }
            else
            {
                return File(renderedBytes, "image/tiff");
            }
        }

        public String dateFrom;
        public String dateTo;

        public ActionResult metodoprueba(string dFrom, string dTo)
        {

            dateFrom = dFrom;
            dateTo = dTo;
            return this.Json(new { Result = "OK", Options = dFrom });
        }
        public ActionResult GetProcess0Options()
        {
            try
            {
                var entities = this.ProcessRepository.GetAll()
                    .Select(c => new Models.SelectListItem { DisplayText = c.PROC_N0_NAME, Value = c.PROC_N0_ID.ToString() });
                return this.Json(new { Result = "OK", Options = entities });
            }
            catch (Exception ex)
            {
                return this.Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

    }
}

DeltaApp/Views/Report5/Index.cshtml
@*<link href="~/Content/site.css" rel="stylesheet" />*@


<link href="~/Content/Views/Product/Index.css" rel="stylesheet" />
<script src="~/Scripts/Views/Product/ShowPreviewInfo.js"></script>
<script src="~/Scripts/Views/Report5/index.js"></script>

@model  DeltaApp.Models.GENERAL_RESUME_VIEW
@{

//Layout = "~/Views/Shared/_Layout.cshtml";
}

<script>
    $(document).ready(function () {
        // Inicializar productos.
        Report5Index.initializeComponents();
    });
</script>

<script type="text/javascript">
</script>





@*@using (Html.BeginForm(new { ReturnUrl = ViewBag.ReturnUrl }))*@
@using (Html.BeginForm("Index", "Report5", FormMethod.Post, new { id = "formReport1" }))
{


    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div>
        <div>
            <h2 class="h2">Reporte Resumen General</h2>
        </div>
    </div>
        <div>
            <div>
                <br />
                <fieldset>


                    <legend id="lgnCustomer" class="desc">
                        Seleccione Fecha
                    </legend>

                    <div>
                        <label class="desc" id="lblFromDate" for="txtFromDate">
                            Desde *
                        </label>
                        <div>
                            <input id="txtFromDate" name="txtFromDate" type="text" value="" class="validate[required, custom[date]]">
                        </div>
                    </div>

                    <div>
                        <label class="desc" id="lblToDate" for="txtToDate">
                            Hasta *
                        </label>
                        <div>
                            <input id="txtToDate" name="txtToDate" type="text" value="" class="validate[required, custom[date]]">
                        </div>
                    </div>
                    <br />

                    <div>
                        <div style="text-align: center;">
                            <input id="btnGenerateReport" name="btnGenerateReport" type="submit" value="Crear">
                        </div>
                    </div>

                    <br />
                    <ol>
                        <li>
                            @*@Html.LabelFor("fecha")
                            @Html.TextBoxFor(m => m.MSR_DATE)
                            @Html.ValidationMessageFor(m => m.PDT_NAME)*@

                        </li>
                    </ol>
                   @* <input type="submit"  id="btnSubmit" value="View Report" />*@
                </fieldset>

                
            </div>

            
        </div>

}
@*<embed id ="pdfViwer" src="/pdf/sample-3pp.pdf#page=2" type="application/pdf" width="100%" height="100%">*@

@using ReportViewerForMvc;
@*@Html.ReportViewer(ViewBag.ReportViewer as Microsoft.Reporting.WebForms.ReportViewer)*@
<div>
    <div id="reportView" style="background: rgb(69, 69, 69);">

        <img id="reportJPG" />

    </div>
</div>



</rsweb:ReportViewer>

@if (Model != null)
{

    <section class="social" id="ReportDisplayPanel">
        <h4>Report Viewer Section.</h4>
        @Html.ActionLink("View Report in PDF Format", "GenerateAndDisplayReport", new { territory = Model.PDT_NAME, format = "pdf" })
        @Html.ActionLink("Download Report in PDF Format", "DownloadReport", new { territory = Model.PDT_NAME, format = "pdf" })
        <img src="@Url.Action("GenerateAndDisplayReport", "Report1", new { territory = Model.PDT_NAME, format = Model.PROC_N0_NAME })" />
      
    </section>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}