DeltaApp/Controllers/AreaController.cs
using DeltaApp.DAL;
using DeltaApp.Models;
using DeltaApp.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DeltaApp.ContArealers
{
    public class AreaController : Controller
    {
        AreaRepository AreaRepository = new AreaRepository(new DataContext());

        public ActionResult Index()
        {
            return View();
        }

        #region Metodos jTable
        /// <summary>
        /// Obtener usuarios.
        /// </summary>
        /// <param name="name">Nombre de usuario</param>
        /// <param name="jtStartIndex"></param>
        /// <param name="jtPageSize"></param>
        /// <param name="jtSorting"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult GetAreas(string name = "", int jtStartIndex = 0, int jtPageSize = 0, string jtSorting = null)
        {
            ActionResult result = null;
            try
            {
                //Lista de usuario con filtro
                var Areas = this.AreaRepository.GetAreas(name, jtStartIndex, jtPageSize, jtSorting);
                //Conteo de usuario con filtros
                var AreaCount = this.AreaRepository.GetAreasCount(name);
                //Resultado para contArea de jtable.
                result = Json(new { Result = "OK", Records = Areas.ToList(), TotalRecordCount = AreaCount }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                result = Json(new { Result = "ERROR", Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
            return result;
        }

        /// <summary>
        /// Crear nuevo tipo de servicio.
        /// </summary>
        /// <param name="areaInfo">Informacion de usuario</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult CreateArea(AREA_VIEW areaInfo)
        {
            ActionResult result = null;
            string resultMessage = string.Empty;
            try
            {
                if (!this.ModelState.IsValid)
                {
                    throw new Exception("Form is not valid! Please correct it and try again.");
                }
                resultMessage = this.AreaRepository.Insert(areaInfo);
                if (string.IsNullOrEmpty(resultMessage))
                {
                    result = this.Json(new { Result = "OK", Record = areaInfo }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    result = this.Json(new { Result = "ERROR", Message = resultMessage }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                result = this.Json(new { Result = "ERROR", Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
            return result;
        }

        /// <summary>
        /// Actualizar tipo de servicio
        /// </summary>
        /// <param name="AreaInfo">Informacion de tipo de servicio</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult UpdateArea(AREA_VIEW AreaInfo)
        {
            ActionResult result = null;
            string resultMessage = string.Empty;
            try
            {
                if (!this.ModelState.IsValid)
                {
                    throw new Exception("Form is not valid! Please correct it and try again.");
                }
                resultMessage = this.AreaRepository.Update(AreaInfo);
                if (string.IsNullOrEmpty(resultMessage))
                {
                    result = Json(new { Result = "OK" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    result = Json(new { Result = "ERROR", Message = resultMessage }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                result = Json(new { Result = "ERROR", Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
            return result;
        }

        /// <summary>
        /// Eliminar Area de usuario
        /// </summary>
        /// <param name="Area_ID">Id de Area de usuario</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult DeleteArea(int Area_ID)
        {
            ActionResult result = null;
            string resultMessage = string.Empty;
            try
            {
                resultMessage = this.AreaRepository.Delete(Area_ID);
                if (string.IsNullOrEmpty(resultMessage))
                {
                    result = this.Json(new { Result = "OK" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    result = this.Json(new { Result = "ERROR", Message = resultMessage }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                result = this.Json(new { Result = "ERROR", Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
            return result;
        }
        #endregion Metodos jTable
    }
}

DeltaApp/Views/Area/Index.cshtml
<link href="~/Content/Views/Area/Index.css" rel="stylesheet" />

<script src="~/Scripts/Views/Area/Index.js"></script>

<script type="text/javascript">
    $(window).load(function () { $("#spinner").fadeOut("slow"); })
    $(document).ready(function () {
        var listCmd = '@this.Url.Action("GetAreas", "Area")';
        var deleteCmd = '@this.Url.Action("DeleteArea", "Area")';
        var updateCmd = '@this.Url.Action("UpdateArea", "Area")';
        var createCmd = '@this.Url.Action("CreateArea", "Area")';
        AreaIndex.initializeComponents(listCmd, deleteCmd, updateCmd, createCmd);
    });
</script>
@using (Html.BeginForm("Index", "Area", FormMethod.Post, new { id = "formArea" }))
{
    <div>
        <div>
            <h2 class="h2">Areas</h2>
        </div>
    </div>

    <div>
        <div>
            <table style="width: 100%; text-align: center;">
                <tr>
                    <td>
                        <input id="txtName" name="txtName" placeholder="Nombre" type="text" />
                    </td>
                </tr>
            </table>
            <hr />
            <table style="width: 100%; text-align: center;">
                <tr>
                    <td>
                        <input type="submit" id="btnIndex" value="Atrás" class="input button" />
                        <input type="submit" id="btnSearch" value="Buscar" class="input button" />
                        <input type="submit" id="btnNewSearch" value="Nueva Busqueda" class="input button" />
                    </td>
                </tr>
            </table>
        </div>
    </div>
    <div>
        <div>
            <hr />
        </div>
    </div>
    <div id="divAreaTableContainerValue"></div>
    <div id="divDivisionContainer" style="display:none;">
        <div id="divDivisionN1TableContainer">
            <div id="divDivisionN1TableContainerValue"></div>
        </div>
    </div>
}